discord:
  # Default ping for all sites (can be overridden per site)
  ping: ""

scan_interval: 30
page_timeout: 30

sites:
  - scan_url: "https://howl.gg"
    notify_url: "https://howl.gg/r/degdeg"
    keywords: ["rain", "raining"]
    webhook_url: "https://discord.com/api/webhooks/1489930398560686144/DZiVOsFDIukQIYbSRZfkaMNlpfUsjiQMKSpKYxl1GHl2-CdkUTTowXNAAOM_VF1YgBVW"

  - scan_url: "https://bandit.camp"
    notify_url: "https://bandit.camp/r/iamfree"
    keywords: ["rain", "raining"]
    webhook_url: "https://discord.com/api/webhooks/1489790133707341956/3ccDVxRMZcyx5KSS4C7rXgVfU2t6wfvjzEM71wMzFg6KrX8LS3uT5GS4jGOoeZXLJaeI"
